language: php

php:
    - 7.1
    - nightly

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

cache:
    directories:
        - vendor

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer update --prefer-dist

script:
    - composer validate --strict

    - vendor/bin/ecs check tests --config fixers/standard.neon
    - vendor/bin/ecs check tests --config fixers/risky.neon
